### ISSUE TITLE
red-stderr.c can only work in debug mode

### ISSUE THREAD

**Issue by APIPLM** [lassik/junkcode#1]
@lassik Can you take a little time to see if there is something about what I said? As I run red-stderr.c, it hang on, without anything output in the console. like `./red-stderr ls`, but when run it in debug mode, I mean that in gdb `set follow-fork-mode child`, then the  ouput come out.
Thanks in advance.

**Comment by lassik** [comment]
Thanks fo the interest. Fixed in commit 1fbbda1. I cleaned up the rest of the program as well; it was very old code. Check the `master` branch for the latest code. Let me know if you have other improvements to it.

One thing is that it relies on the output from the subprocess to be line-buffered. If the subprocess sends a partial line of text so that the line is split in half, then red-stderr will also output partial lines instead of waiting for a full line.

**Comment by APIPLM** [comment]
@lassik  Thanks. Stop compiling.
```
[root@haiwen unix]# gcc -Wall -Wextra -std=c99 -g -O -o red-stderr red-stderr.c
red-stderr.c: In function ‘run’:
red-stderr.c:77:22: error: storage size of ‘sa’ isn’t known
     struct sigaction sa;
                      ^
red-stderr.c:85:5: warning: implicit declaration of function ‘sigaction’ [-Wimplicit-function-declaration]
     sigaction(SIGCHLD, &sa, 0);
     ^
red-stderr.c:77:22: warning: unused variable ‘sa’ [-Wunused-variable]
     struct sigaction sa;
```

**Comment by lassik** [comment]
`sigaction` should come from `#include <signal.h>`. Which OS are you using? Try `-std=gnu99` instead of `std=c99`; it sometimes helps when the compiler does not find a standard function.

**Comment by APIPLM** [comment]
The OS is CentOS 7. Now it works. Thanks very much

**Comment by APIPLM** [comment]
Just a little bit funny thing to share with you.
```
#include <stdio.h>
int main(){
 fprintf(stdout,"Hello ");
 fprintf(stderr,"World!");
 return 0;
 }
```
If you have the above code to build one exe like test. The result is different by running between `./red-stderr ./test`   and `./test`.

**Comment by lassik** [comment]
That's neat!

This will make it show them in the same order:

```
fprintf(stdout, "Hello ");
fflush(stdout);
fprintf(stderr, "World!");
```

By default, stdout is line-buffered but stderr is unbuffered. So `fprintf(stderr, ...)` will write the output immediately. But `fprintf(stdout, ...)` will delay the writing until there is a full line of text, i.e. `\n` in the string. If there is no `\n`, it will only write the output at the end of the program. `fflush()` forces it to write immediately.

red-stderr does this:

```
            if (fds[0].revents & POLLIN)
                read_from_fd(stdout_pipe[0], color_reset);
            if (fds[1].revents & POLLIN)
                read_from_fd(stderr_pipe[0], color_red);
```

So when there is data available on both stdout (fds[0) and stderr (fds[1]) at the same time, it will first copy the data from stdout, then the data from stderr. Even the subprocess wrote them in the opposite order. As long as they arrived to red-stderr at the same time.
